### ISSUE TITLE
Error 404.

### ISSUE THREAD

**Issue by BarnumD** [patrontech/devops-tf-cloud-update-var#1]
We're attempting to use this action and we're getting 
`Error: Request failed with status code 404`.  Do you have any idea where the 404 would be coming from?
```
      - name: Update MPDX image version variable in Terraform Cloud
        uses: patrontech/devops-tf-cloud-update-var@v1.0.1
        with:
          workSpaceName: 'our-workspace-name'
          organizationName: 'our-org-name'
          terraformToken: ${{secrets.TERRAFORM_TOKEN}}
          terraformHost: 'app.terraform.io'
          variableName: 'our_variable_name'
          variableValue: '5834964371-107-1'
```
